package avion;

public enum PlaneMessageType {
    WHERE_AM_I,
    SEND_WARNING_PLANE_COLLISION,
    SEND_DECISION_PLANE_COLLISION,
    ASK_LTC_GATEWAY,
    ASK_ATC_GATEWAY,
    FILL_PLANE,
    TAKE_OF,
    WAIT_TAKE_OF,
    IM_FLYING,
    ATC_LAND_RESPONSE_APPROVAL,
    ATC_LAND_RESPONSE_REJECT,
    LAND,
    WAIT_LAND
}
