package ltc;

public enum LaneTrafficControlMessageType {
    PLANE_RUNWAY_TAKEOFF_REQUEST,
    ATC_RUNAWAY_REQUEST_RESPONSE_APPROVE,
    ATC_RUNAWAY_REQUEST_RESPONSE_REQUEST_WAIT,
    PLANE_GATEWAY_REQUEST,
    PLANE_UNLOAD_PASSENGERS_END_ITINERARY
}
